### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by NorthSummer** [ercanburak/HyperE2VID#3]
Hi, I have a quesiton about the training data. I guess the data is generated with the same method as this work: https://timostoff.github.io/20ecnn. However, I found it difficult to generate high-quality event data using its method. May I ask your plan about release the related train data? Thanks very much!

**Comment by ercanburak** [comment]
Hi, and thank you for your interest in our work.

You are right; the training data is generated using the same method as https://timostoff.github.io/20ecnn. 

I was not planning to release the training data (which might be hard due to its size), but I am receiving questions about this, so I might add our own version of dataset generation scripts, config files, and instructions sometime. I will post an update on this issue if I do.

**Comment by EE102-JN** [comment]
Dear Burak, Thank you for your response. I have also carefully reviewed your EVREAL repository, which focuses on event-based evaluation. It has been incredibly helpful. Nevertheless, we have encountered a few challenges that we hope to get your insights on.

Firstly, we are facing a discrepancy in data resolution. Our events are generated from the COCO dataset with a resolution of 256x256, whereas the test data typically has a resolution of 180x240. Could you suggest how we might address this mismatch?

Secondly, we've observed that our generated data appears normal only when we set the event_voxel_channel to 1. If we alter this setting, the events become very sparse during data loading. Do you have any recommendations on how we can improve this?

Lastly, we noticed that the foreground and background data from COCO are randomly selected, implying that each generation leads to a different training set. Is this variation expected, and how should we account for it in our evaluations?

Your guidance on these matters would be greatly appreciated. Best Regards~

**Comment by ercanburak** [comment]
Dear @EE102-JN, thank you for your interest in our work.

1) HyperE2VID (and many other event-based video reconstruction networks) can work with various resolutions (in fact, they work at any resolution as long as the dimensions are multiples of 8 or 16, etc.). So the mismatch between the resolutions of training and test data should not cause errors during inference. Furthermore, we use random crops during training, therefore the network never sees data with a resolution of 256x256 during training anyway. Finally, it is possible to generate training data at a different resolution via ESIM, as done in the E2VID paper (they generate the training data at 180x240 resolution).

2) The event data is inherently sparse (generated sparsely, in contrast to frames), and the sparseness of it depends on camera parameters, motion, and scene edges (like object edges or texture). So the sparsity you see might not be "something you need to improve". If you are referring to the sparseness in some event representation (like an event voxel grid), then please keep in mind that it also depends on how you group events to form the representation (like constant duration, constant event number, etc.)

3) You can use a predetermined set of images from COCO, as explained in **Generating datasets from existing configs section** in [here](https://github.com/TimoStoff/esim_config_generator/tree/master?tab=readme-ov-file#generating-datasets-from-existing-configs).

**Comment by NorthSummer** [comment]
> Dear @EE102-JN, thank you for your interest in our work.
> 
> 1. HyperE2VID (and many other event-based video reconstruction networks) can work with various resolutions (in fact, they work at any resolution as long as the dimensions are multiples of 8 or 16, etc.). So the mismatch between the resolutions of training and test data should not cause errors during inference. Furthermore, we use random crops during training, therefore the network never sees data with a resolution of 256x256 during training anyway. Finally, it is possible to generate training data at a different resolution via ESIM, as done in the E2VID paper (they generate the training data at 180x240 resolution).
> 2. The event data is inherently sparse (generated sparsely, in contrast to frames), and the sparseness of it depends on camera parameters, motion, and scene edges (like object edges or texture). So the sparsity you see might not be "something you need to improve". If you are referring to the sparseness in some event representation (like an event voxel grid), then please keep in mind that it also depends on how you group events to form the representation (like constant duration, constant event number, etc.)
> 3. You can use a predetermined set of images from COCO, as explained in **Generating datasets from existing configs section** in [here](https://github.com/TimoStoff/esim_config_generator/tree/master?tab=readme-ov-file#generating-datasets-from-existing-configs).

Dear Burak, thanks so much for the reply, it's very helpful. Just one more question~ When we generate event data using this method [esim-config-generator](https://github.com/TimoStoff/esim_config_generator/tree/master?tab=readme-ov-file#generating-datasets-from-existing-configs), the parameter settings are --contrast_threshold_mean=1.0 --contrast_threshold_sigma=0.1. Can this configuration produce normal event data? Or we should dynamically set --contrast_threshold_mean and --contrast_threshold_sigma? Thank you again for reading this message!

**Comment by ercanburak** [comment]
Dear @NorthSummer. Contrast threshold is an important parameter for event cameras. In simple terms, it indicates the sensitivity of the event sensor. A lower contrast threshold means a higher sensitivity (therefore more events are generated). It is not a fixed quantity, the exact value of it depends on many things, and it can be modeled via a probability distribution such as a Gaussian. I suggest reading Section 2.4 of the [Event-based Vision Survey paper](https://arxiv.org/abs/1904.08405) and the [paper originally suggesting this training dataset](https://arxiv.org/abs/2003.09078), to gain more insight.

The `esim_config_generator` is a tool to generate random config files (given a set of parameters, like the mean and sigma you mention). These randomly generated config files can then be used to set options of ESIM (including contrast threshold). The mean and sigma values of 1.0 and 0.1 are plausible values (depending on what you want). However, if you want to generate the exact training dataset of HyperE2VID, you can use the existing config files instead of randomly generating them (as explained in **Generating datasets from existing configs** section of `esim_config_generator`.

I have now added my own scripts, configs, and instructions to generate the training set used to train HyperE2VID. You can find them in the [datagen folder](https://github.com/ercanburak/HyperE2VID/tree/main/datagen).

**Comment by NorthSummer** [comment]
Dear Burak, thank you very much for these replies, which are greatly helpful to us. We will carefully consider your instructions and use your script to generate the training data again. Thank you once again, and wish you more progress in your research!
